
#ifndef _LIBSCOMMON_H_
#define _LIBSCOMMON_H_

//Linux...
#ifdef __cplusplus
extern "C"
{
#endif
//#include <libavcodec/avcodec.h>
//#include <libavdevice/avdevice.h>
//#include <libavutil/avutil.h>
//#include <libavformat/avformat.h>
//#include <libavfilter/avfilter.h>
//#include <libswscale/swscale.h>
//#include <libavdevice/avdevice.h>
//#include <libavutil/mathematics.h>
//#include <libavutil/time.h>
//#include <libavutil/pixfmt.h>
//#include <SDL2/SDL.h>
#ifdef __cplusplus
};
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <iostream>
#include <queue>
#include <sys/types.h>
#include <sys/mman.h>
#include <linux/videodev2.h>
#include<sys/epoll.h>

#include <ptlib.h>
#include <ptlib/pprocess.h>
#include <ptlib/sockets.h>

#include <sys/socket.h>
#include <errno.h>
#include <netinet/in.h>

#include "debug.h"
//#include "autogenerated.h"
#if 0
#ifdef _WIN32
#define PATH_SEPARATOR "\\"
#else
#define PATH_SEPARATOR "/"
#endif
//aka the /opt/xxx/bin/../
#if defined CONFIG_ARCH_x64
#define WORK_PATH (PProcess::Current().GetFile().GetVolume() + PProcess::Current().GetFile().GetPath())
#elif defined CONFIG_ARCH_3516 || defined CONFIG_ARCH_3519 || defined CONFIG_ARCH_3559
#define WORK_PATH (PProcess::Current().GetFile().GetVolume() + PProcess::Current().GetFile().GetPath() + PATH_SEPARATOR + PString(".."))
#endif
#define CONFIG_PATH (WORK_PATH + PATH_SEPARATOR + PString("config"))

#define DEFAULT_THREAD_STACK_SIZE (1024 * 1024 * 4)

#define	min(x1, x2) (((x1)<(x2))?(x1):(x2))
#define CLEAR(x) memset (&(x), 0, sizeof (x))

#define PCONTAINS(pstring, subStr) (P_MAX_INDEX != pstring.Find(subStr))

#endif
typedef enum {
	SUCCESS = 0,
	OPENFAIL,
	OVERSIZE,
	READFAIL,
	UNKNOWN
} ERROR_CODE;

#endif

